version: '3.8'

services:
  # Backend NestJS - OPTIMISÉ
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ci_mandat_backend_prod
    environment:
      # Environnement
      NODE_ENV: production
      PORT: 3001
      
      # Base de données
      DATABASE_URL: postgresql://ci_mandat_user:CiMandatProd2024SecureDBPass@ci_mandat_postgres_prod:5432/ci_mandat_db?sslmode=disable
      
      # Authentification JWT
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_EXPIRES: 15m
      JWT_REFRESH_EXPIRES: 7d
      
      # Chiffrement
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      DATA_ENCRYPTION_IV: ${DATA_ENCRYPTION_IV}
      
      # Redis
      REDIS_HOST: ci_mandat_redis_prod
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      
      # URLs
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_URL: ${BACKEND_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      
      # Sécurité
      RATE_LIMIT_WINDOW: 900000
      MAX_LOGIN_ATTEMPTS: 5
      SESSION_TIMEOUT: 3600000
      
      # Logging
      LOG_LEVEL: info
      LOG_FORMAT: json
      
      # Performance
      NODE_OPTIONS: "--max-old-space-size=512"
    ports:
      - "3001:3001"
    volumes:
      - pdf_storage_prod:/app/storage/pdfs
      - backend_logs:/app/logs
    networks:
      - ci_mandat_network_prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pdf_storage_prod:
    driver: local
  backend_logs:
    driver: local

networks:
  ci_mandat_network_prod:
    external: true
    name: ci_mandat_prod_ci_mandat_network_prod